### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by scottdavis** [robbywashere-zz/sass-base64-encoder#1]
Would you mind if i used some of this in compass trying to piece together a way to get to libsass compatibility and this would be a huge help! Only asking because I didn't see a license.

**Comment by robbywashere-zz** [comment]
Yeah absolutely. It could probably be improved a good deal as well. Also, I took a good deal of code for the bitwise functions from this repo: https://github.com/HugoGiraudel/SassyBitwise
